// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr0gpZKDDARxACxOYmH4U8tmLz1XPXKzE',
    appId: '1:57002270581:web:e240481885b93496687d3c',
    messagingSenderId: '57002270581',
    projectId: 'fleet-notification-system',
    authDomain: 'fleet-notification-system.firebaseapp.com',
    storageBucket: 'fleet-notification-system.firebasestorage.app',
    measurementId: 'G-G6153L2MMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCzSBNu-a5paVXPOKWtTcSTRkQ2bfGGLU',
    appId: '1:57002270581:android:017b41ab21f6bae7687d3c',
    messagingSenderId: '57002270581',
    projectId: 'fleet-notification-system',
    storageBucket: 'fleet-notification-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjZ_qP8SCeHzcIvgb98wq-TzTxx2qXw7E',
    appId: '1:57002270581:ios:3cc1c89945d63e8e687d3c',
    messagingSenderId: '57002270581',
    projectId: 'fleet-notification-system',
    storageBucket: 'fleet-notification-system.firebasestorage.app',
    iosBundleId: 'com.example.v2x',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr0gpZKDDARxACxOYmH4U8tmLz1XPXKzE',
    appId: '1:57002270581:web:97291e73398a1a2b687d3c',
    messagingSenderId: '57002270581',
    projectId: 'fleet-notification-system',
    authDomain: 'fleet-notification-system.firebaseapp.com',
    storageBucket: 'fleet-notification-system.firebasestorage.app',
    measurementId: 'G-NJM5HHDZD6',
  );
}
